---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: faas-controller
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
data:
  nats-config: |+
    max_payload: 10485760
    streaming {
      store_limits {
        max_msgs: 0
        max_bytes: 0
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name:  nats
        image: nats-streaming:0.11.2
        imagePullPolicy: Always
        ports:
        - containerPort: 4222
          protocol: TCP
        - containerPort: 8222
          protocol: TCP
        command: ["/nats-streaming-server"]
        args:
          - --store
          - memory
          - --cluster_id
          - faas-cluster
          - -m
          - "8222"
          - -sc
          - /etc/nats-config
        volumeMounts:
        - mountPath: /etc/nats-config
          name: nats-config
          subPath: nats-config
      volumes:
      - configMap:
          name: nats-config
        name: nats-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway    
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: faas-controller
      containers:
      - name: gateway
        image: openfaas/gateway:0.11.1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 10
          timeoutSeconds: 2

        env:
        - name: functions_provider_url
          value: "http://127.0.0.1:8081/" # Final `.` specifies an absolute address
        - name: faas_nats_address
          value: "nats.openfaas.svc.cluster.local."
        - name: faas_nats_port
          value: "4222"
        - name: direct_functions
          value: "true"                             # Functions are invoked directly over the overlay network
        - name: direct_functions_suffix
          value: "openfaas-fn.svc.cluster.local."   # contains K8s namespace
        - name: read_timeout
          value: "600s"
        - name: write_timeout
          value: "600s"
        - name: upstream_timeout  # Must be smaller than read/write_timeout
          value: "600s"
        - name: basic_auth
          value: "true"
        - name: secret_mount_path
          value: "/etc/openfaas"
        - name: scale_from_zero
          value: "false"
        - name: max_idle_conns
          value: "1024"
        - name: max_idle_conns_per_host
          value: "1024"
        - name: faas_nats_address
          value: "nats"
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/openfaas
          name: gateway-basic-auth
          readOnly: true
        resources:
          requests:
            memory: 250Mi
          limits:
            memory: 250Mi   # Adjust to suit needs of deployment
      - name: faas-netes
        image: openfaas/faas-netes:0.7.0
        imagePullPolicy: Always
        env:
        - name: port
          value: "8081"
        - name: function_namespace
          value: openfaas-fn
        - name: read_timeout
          value: "600s"
        - name: write_timeout
          value: "600s"
        ports:
        - containerPort: 8081
          protocol: TCP
      volumes:
      - name: gateway-basic-auth
        secret:
          defaultMode: 420
          secretName: gateway-basic-auth
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31112
  selector:
    app: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: openfaas
  labels:
    app: nats
spec:
  type: NodePort
  ports:
  - name: "4222"
    nodePort: 32677
    port: 4222
    protocol: TCP
    targetPort: 4222
  - name: "8222"
    nodePort: 31118
    port: 8222
    protocol: TCP
    targetPort: 8222
  selector:
    app: nats
#apiVersion: v1
#kind: Service
#metadata:
#  name: nats
#  labels:
#    app: nats
#spec:
#  type: ClusterIP
#  ports:
#    - port: 4222
#      protocol: TCP
#      targetPort: 4222
#      name: clients
#    - port: 8222
#      protocol: TCP
#      targetPort: 8222
#      name: monitoring
#  selector:
#    app: nats
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-worker
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: queue-worker
#  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: queue-worker
    spec:
      containers:
      - name:  queue-worker
        image: openfaas/queue-worker:0.7.0
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: max_inflight      # Max number of items in-flight
          value: "1"
        - name: ack_wait          # Max duration of any async task / request
          value: "600s"
        - name: faas_function_suffix
          value: ".openfaas-fn.svc.cluster.local."  # absolute DNS will suppress search domains
        - name: basic_auth
          value: "false"
        - name: secret_mount_path
          value: "/etc/openfaas"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: faasdmmt-controller
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: faasdmmt-controller-fn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: faasdmmt-controller

subjects:
- kind: ServiceAccount
  name: faasdmmt-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: faasdmmt-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-dmmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-dmmt
  template:
    metadata:
      labels:
        app: nats-dmmt
    spec:
      containers:
      - name:  nats-dmmt
        image: nats-streaming:0.11.2
        imagePullPolicy: Always
        ports:
        - containerPort: 4222
          protocol: TCP
        - containerPort: 8222
          protocol: TCP
        command: ["/nats-streaming-server"]
        args:
          - --store
          - memory
          - --cluster_id
          - faas-cluster
          - -m
          - "8222"
          - -sc
          - /etc/nats-config
        volumeMounts:
        - mountPath: /etc/nats-config
          name: nats-config
          subPath: nats-config
      volumes:
      - configMap:
          name: nats-config
        name: nats-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-dmmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-dmmt
  template:
    metadata:
      labels:
        app: gateway-dmmt
    spec:
      serviceAccountName: faasdmmt-controller
      containers:
      - name: gateway-dmmt
        image: openfaas/gateway:0.11.1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 10
          timeoutSeconds: 2
        env:
        - name: functions_provider_url
          value: "http://127.0.0.1:8081/" # Final `.` specifies an absolute address
        - name: faas_nats_address
          value: "nats-dmmt.openfaas.svc.cluster.local."
        - name: faas_nats_port
          value: "4222"
        - name: direct_functions
          value: "true"                             # Functions are invoked directly over the overlay network
        - name: direct_functions_suffix
          value: "openfaas-fn.svc.cluster.local."   # contains K8s namespace
        - name: read_timeout
          value: "600s"
        - name: write_timeout
          value: "600s"
        - name: upstream_timeout  # Must be smaller than read/write_timeout
          value: "600s"
        - name: basic_auth
          value: "true"
        - name: secret_mount_path
          value: "/etc/openfaas"
        - name: scale_from_zero
          value: "false"
        - name: max_idle_conns
          value: "1024"
        - name: max_idle_conns_per_host
          value: "1024"
        - name: faas_nats_address
          value: "nats-dmmt"
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/openfaas
          name: gateway-basic-auth
          readOnly: true
        resources:
          requests:
            memory: 250Mi
          limits:
            memory: 250Mi   # Adjust to suit needs of deployment
      - name: faas-netes-dmmt
        image: openfaas/faas-netes:0.7.0
        imagePullPolicy: Always
        env:
        - name: port
          value: "8081"
        - name: function_namespace
          value: openfaas-fn
        - name: read_timeout
          value: "600s"
        - name: write_timeout
          value: "600s"
        ports:
        - containerPort: 8081
          protocol: TCP
      volumes:
      - name: gateway-basic-auth
        secret:
          defaultMode: 420
          secretName: gateway-basic-auth
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-dmmt
  labels:
    app: gateway-dmmt
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: gateway-dmmt
---
apiVersion: v1
kind: Service
metadata:
  name: nats-dmmt
  labels:
    app: nats-dmmt
spec:
  type: ClusterIP
  ports:
    - port: 4222
      protocol: TCP
      targetPort: 4222
      name: clients
    - port: 8222
      protocol: TCP
      targetPort: 8222
      name: monitoring
  selector:
    app: nats-dmmt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-worker-dmmt
spec:
  #replicas: 10
  selector:
    matchLabels:
      app: queue-worker-dmmt
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: queue-worker-dmmt
    spec:
      containers:
      - name:  queue-worker-dmmt
        image: openfaas/queue-worker:0.7.0
        imagePullPolicy: Always
        env:
        - name: max_inflight      # Max number of items in-flight
          value: "1"
        - name: ack_wait          # Max duration of any async task / request
          value: "600s"
        - name: faas_function_suffix
          value: ".openfaas-fn.svc.cluster.local."  # absolute DNS will suppress search domains
        - name: basic_auth
          value: "false"
        - name: secret_mount_path
          value: "/etc/openfaas"
        - name: faas_nats_address
          value: "nats-dmmt"
