apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: marvin
spec:
  serviceName: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      tolerations:
      - key: dedicated
        operator: Equal
        value: storage-node
        effect: NoExecute
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                  - elasticsearch
            topologyKey: kubernetes.io/hostname
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: datadir
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: cr-preview.pentium.network/elasticsearch:6.8.0
        imagePullPolicy: "IfNotPresent"
        env:
        - name: discovery.type
          value: single-node
        - name: "ES_JAVA_OPTS"
          value: "-Xms3g -Xmx3g"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        #securityContext:
        #  privileged: true
        volumeMounts:
        - name: datadir
          mountPath: "/usr/share/elasticsearch/data"
        #securityContext:
        #   privileged: true
      volumes:
#       - name: datadir
#         emptyDir: {}
# access permision denied
       - name: datadir
         hostPath:
           path: /opt/elasticsearch
#  volumeClaimTemplates:
#    - metadata:
#        name: datadir
#      spec:
#        accessModes:
#          - ReadWriteOnce
#        storageClassName: "standard"
#        resources:
#          requests:
#            storage: "10Gi"


---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: marvin
  labels:
    service: elasticsearch
spec:
  clusterIP: None
  ports:
    - port: 9200
      targetPort: 9200
      name: http
    - port: 9300
      targetPort: 9300
      name: transport
  selector:
    app: elasticsearch
---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-n
  namespace: marvin
  labels:
    service: elasticsearch-n
spec:
  type: NodePort
  selector:
    app: elasticsearch

  ports:
  - port: 9200
    targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-cluster
  namespace: marvin
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
  - name: transport
    port: 9300

