apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: neo4j-core
  namespace: marvin
spec:
  serviceName: neo4j
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
        component: core
    spec:
      tolerations:
      - key: dedicated
        operator: Equal
        value: storage-node
        effect: NoExecute
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                  - neo4j
            topologyKey: kubernetes.io/hostname
      containers:
      - name: neo4j
        image: cr-preview.pentium.network/neo4j:3.5.8-enterprise
        imagePullPolicy: "IfNotPresent"
        env:
          - name: NEO4J_AUTH
            value: neo4j/pentium
          - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
            value: "yes"
          - name: NEO4J_dbms_memory_pagecache_size
            value: 2G
          - name: NEO4J_dbms_memory_heap_maxSize
            value: 4G
        ports:
        - containerPort: 7474
          name: browser
        - containerPort: 7687
          name: bolt
        securityContext:
          privileged: true
        volumeMounts:
        - name: datadir
          mountPath: "/data"
        - name: import
          mountPath: "/var/lib/neo4j/import"
        - name: plugin
          mountPath: "/plugins"
      volumes:
       - name: datadir
         hostPath:
           path: /opt/neo4j/marvin
       - name: logdir
         hostPath:
           path: /opt/neo4j/logs/marvin
       - name: import
         hostPath:
           path: /opt/neo4j/import/marvin
       - name: plugin
         hostPath:
           path: /opt/neo4j/plugin/marvin
#      nodeSelector:
#        ptnodetype: "datanode"
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: marvin
  labels:
    app: neo4j
    component: core
spec:
  clusterIP: None
  ports:
    - port: 7474
      targetPort: 7474
      name: browser
    - port: 6362
      targetPort: 6362
      name: backup
    - port: 7687
      targetPort: 7687
      name: bolt
  selector:
    app: neo4j
    component: core
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-n
  namespace: marvin
  labels:
    app: neo4j
    component: core
spec:
  ports:
  - name: neo4jconnect
    protocol: TCP
    port: 7474
    targetPort: 7474
  - name: neo4balt
    protocol: TCP
    port: 7687
    targetPort: 7687
  type: NodePort
  selector:
    app: neo4j
    component: core
---
