apiVersion: v1
kind: Service
metadata:
  name: logs
  namespace: openfaas-fn
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    faas_function: logs
  sessionAffinity: None
  type: ClusterIP
---
#apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    faas_function: logs
  name: logs
  namespace: openfaas-fn
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      faas_function: logs
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      creationTimestamp: null
      labels:
        faas_function: logs
      name: logs
    spec:
      containers:
      - image: cr.pentium.network/logs:0.157.1.20191029170757
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: x-health-check
              value: /health
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: logs
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: x-health-check
              value: /healthz
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          procMount: Default
          readOnlyRootFilesystem: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/openfaas/secrets
          name: logs-projected-secrets
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: logs-projected-secrets
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: config.json
                path: config.json
              name: pn-faas-secret
