apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: default-http-backend
    name: default-http-backend
    namespace: ingress-nginx
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: default-http-backend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
